name: Add changes to release stages

on:
  push:
    branches:
      - main

jobs:
  merge-changes-to-all-stages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: checkout@v4