name: Add changes to DEV stage

on:
  push:
    branches:
      - main

jobs:
  merge-changes-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: stages/dev

      - name: Merge changes to DEV
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: Merge changes to DEV stage