name: Add changes to DEV stage

on:
  push:
    branches:
      - main

jobs:
  merge-changes-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: stages/qa

      - name: Fetch latest changes from main
        run: |
          git pull origin main:main

      - name: Merge changes to QA
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: Merge changes to QA stage